---
title: "\\textbf{\\textcolor{mycolor}{Budowanie portfela inwestycyjnego}}"
author: "Autor"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    latex_engine: xelatex
header-includes:
   - \usepackage{xcolor}
   - \usepackage{titlesec}
   - \definecolor{mycolor}{HTML}{1E90FF}
   - \titleformat{\section}[block]{\normalfont\Large\bfseries\color{mycolor}}{}{0em}{}

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("kableExtra")) install.packages("kableExtra")
if (!require("readxl")) install.packages("readxl")

library(e1071) #do skosnosci i kurtozy
library(knitr)
library(quantmod)
library(readxl)
library(kableExtra)
```

```{r}
# zalaczenie danych z pliku inwestycje_all.xlsx

library(readxl)

# Import pliku bez pełnej ścieżki
plik <- "inwestycje_all.xlsx"

ccc_all <- read_excel(plik, sheet = 1)
ccc_close <- read_excel(plik, sheet = 2)

vnq_all <- read_excel(plik, sheet = 4)
vnq_close <- read_excel(plik, sheet = 5)

mcpa_all <- read_excel(plik, sheet = 7)
mcpa_close <- read_excel(plik, sheet = 8)

soczek_all <- read_excel(plik, sheet = 10)
soczek_close <- read_excel(plik, sheet = 11)
```


```{r}
# rameczka danych ze stópkami logarytmicznymiiiiuiuiiu

returns_data <- na.omit(cbind(
  CCC = ccc_close$`St. Log`,
  VNQ = vnq_close$St.log,
  OrangeJuice = soczek_close$St.log,
  LVMH = mcpa_close$St.log
))
```



# 3. wartosc wspolczynnikow korelacji

```{r}
# Macierz korelacji
cor_matrix <- cor(returns_data)


# Dane macierzy korelacji
cor_matrix <- data.frame(
  CCC = c(1.00000000, 0.02625213, -0.08289124, 0.01699572),
  VNQ = c(0.02625213, 1.00000000, -0.09297469, 0.02495983),
  OrangeJuice = c(-0.08289124, -0.09297469, 1.00000000, 0.03478741),
  LVMH = c(0.01699572, 0.02495983, 0.03478741, 1.00000000)
)
rownames(cor_matrix) <- c("CCC", "VNQ", "OrangeJuice", "LVMH")


colnames(cor_matrix) <- c(
  cell_spec("CCC", bold = TRUE, color = "forestgreen"),
  cell_spec("VNQ", bold = TRUE, color = "navy"),
  cell_spec("OrangeJuice", bold = TRUE, color = "orange"),
  cell_spec("LVMH", bold = TRUE, color = "red")
)
rownames(cor_matrix) <- c(
  cell_spec("CCC", bold = TRUE, color = "forestgreen"),
  cell_spec("VNQ", bold = TRUE, color = "navy"),
  cell_spec("OrangeJuice", bold = TRUE, color = "orange"),
  cell_spec("LVMH", bold = TRUE, color = "red")
)

kbl(
  cor_matrix,
  escape = FALSE, 
  caption = "Macierz korelacji stóp zwrotu dla wybranych inwestycji",
  align = "c"
) %>%
  kable_styling(full_width = FALSE, position = "center")

# to kolorowanie chat mi wypluł --- sama tak nie umiem zrobić :DDDDD

```





